### ISSUE TITLE
wrong drop amount

### ISSUE THREAD

**Issue by Gandalf360one** [BoBkiNN/ClickHarvest#2] opened 2023-06-24 19:30 UTC
In minecraft 1.20.1 the plugin wont give the right amount of crops back.
affected is wheat and betroot (every crop with a primary and secondary drop).
Players will only get one crop but more seeds

Tested with plugin version: 1.1-b15-R on a 1.20.1 paper server

**Comment by BoBkiNN** [comment] 2023-06-24 19:50
Added this to TODO.md, will fix as soon as possible.

**Comment by Gandalf360one** [comment] 2023-06-25 03:45
thank you very much!

**Comment by BoBkiNN** [comment] 2023-06-25 16:20
Tested and fixed in new update and all works as intended. Keep in mind that one crop/seed is not dropping because it used to plant new crop

**Closed as completed by BoBkiNN** 2023-06-25 16:20 UTC
Labels: bug
